# Generated by Django 4.1.4 on 2023-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
