# Generated by Django 4.1.4 on 2023-01-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categor',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.category'),
            preserve_default='True',
        ),
    ]
