# Generated by Django 4.1.4 on 2023-01-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_categor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='categor',
            new_name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='auctions.qty'),
            preserve_default='True',
        ),
    ]
