# Generated by Django 4.1.4 on 2023-01-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_qty_rename_categor_listing_category_listing_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Qty',
        ),
    ]
