# Generated by Django 4.1.4 on 2023-02-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='categoryType',
        ),
    ]
