# Generated by Django 4.1.4 on 2023-02-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categoryType',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='auctions.category'),
        ),
    ]
