# Generated by Django 4.1.4 on 2023-02-09 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank='False', max_length=250, null='False')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allComments', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alluserComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
