# Generated by Django 4.1.4 on 2023-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank='False', max_length=250, null='False'),
        ),
    ]
